apiVersion: v1
kind: Namespace
metadata:
  name: airflow

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data-pvc
  namespace: airflow
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
  volumeName: data-pv
  storageClassName: standard


---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: airflow-deployment
  namespace: airflow
spec:
  replicas: 1
  selector:
    matchLabels:
      app: airflow
  template:
    metadata:
      labels:
        app: airflow
    spec:
      containers:
      - name: airflow-webserver
        image: apache/airflow:2.3.0
        ports:
        - containerPort: 8080
      - name: airflow-scheduler
        image: apache/airflow:2.3.0
      # Here, volumes should be specified outside of the containers
      volumes:
      - name: airflow-dags
        persistentVolumeClaim:
          claimName: data-pvc

