# airflow-configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: airflow-config
  namespace: airflow
data:
  airflow.cfg: |
    [core]
    executor = CeleryExecutor
    sql_alchemy_conn = postgresql+psycopg2://airflow:airflow@postgres:5432/airflow
    result_backend = db+postgresql://airflow:airflow@postgres:5432/airflow
    [celery]
    broker_url = redis://redis:6379/0
    result_backend = db+postgresql://airflow:airflow@postgres:5432/airflow
