stages:
  - build
  - deploy

variables:
  DOCKER_IMAGE: your-docker-repo/python-pipeline

build:
  stage: build
  script:
    - docker build -t $DOCKER_IMAGE .
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker push $DOCKER_IMAGE

deploy:
  stage: deploy
  script:
    - |
      if [ "$CI_ENVIRONMENT_NAME" == "local" ]; then
        kubectl apply -f storage.yaml
        kubectl apply -f airflow-deployment.yaml
      elif [ "$CI_ENVIRONMENT_NAME" == "aws" ]; then
        aws eks --region $AWS_REGION update-kubeconfig --name $EKS_CLUSTER_NAME
        kubectl apply -f storage.yaml
        kubectl apply -f airflow-deployment.yaml
      fi

