apiVersion: v1
kind: PersistentVolume
metadata:
  name: data-pv
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/tmp/data"

---
  
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi


# apiVersion: v1
# kind: PersistentVolume
# metadata:
#   name: airflow-pv
# spec:
#   capacity:
#     storage: 20Gi
#   accessModes:
#     - ReadWriteOnce
#   hostPath:
#     path: "/mnt/data/airflow"  # Make sure this directory exists on your node
#   storageClassName: ""

# ---

# apiVersion: v1
# kind: PersistentVolumeClaim
# metadata:
#   name: airflow-pvc
#   namespace: airflow
# spec:
#   accessModes:
#     - ReadWriteOnce
#   resources:
#     requests:
#       storage: 20Gi
#   volumeName: airflow-pv
#   storageClassName: ""

# ---
  
# apiVersion: v1
# kind: PersistentVolume
# metadata:
#   name: data-pv
# spec:
#   capacity:
#     storage: 100Gi
#   accessModes:
#     - ReadWriteOnce
#   hostPath:
#     path: "/mnt/data/pipeline"  # Adjust path accordingly
#   storageClassName: ""
# # 